### PR TITLE
Make tests work on macOS

### LINKED ISSUE #44: Test runner fails to find Google Chrome on macOS
Running `yarn test` fails on my system. The test runner reports that it is unable to find Google Chrome:

```

  2 hooks failed

  direct-custom-storage › before hook

  /Users/robert/other/wombat/node_modules/just-launch-chrome/lib/launcher.js:80

  Rejected promise returned by test. Reason:

  Error {
    message: 'Could not find any Chrome/Chromium executables on this system',
  }

  ensureArgs (node_modules/just-launch-chrome/lib/launcher.js:80:13)
  launch (node_modules/just-launch-chrome/lib/launcher.js:124:30)
  initChrome (test/helpers/initChrome.js:42:62)
  Function.init (test/helpers/testHelper.js:12:21)
  test/direct-custom-storage.js:10:12
```

My laptop is running macOS 11.1 with Google Chrome (Dev) installed to the default location: `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`.

If I modify `initChrome.js` to explicitly specify the path to Chrome then the tests run successfully:

```diff
diff --git a/test/helpers/initChrome.js b/test/helpers/initChrome.js
index 72b5e73..cae7de1 100644
--- a/test/helpers/initChrome.js
+++ b/test/helpers/initChrome.js
@@ -40,7 +40,8 @@ const chromeArgs = [
  */
 async function initChrome() {
   const { browserWSEndpoint, closeBrowser, chromeProcess } = await launch({
-    args: chromeArgs
+    args: chromeArgs,
+    executable: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
   });
   const browser = await Browser.connect(browserWSEndpoint, {
     ignoreHTTPSErrors: true,
```

### PR DESCRIPTION
**Pull request by nfriedly**
This replaces `just-launch-chrome` with `chrome-launcher` and tweaks some of the internals. With this change, all of the tests can find, launch, and then close the browser, and _some_ of them pass. However, the majority of tests still fail on my mac. Here's a copy of the logs: https://gist.github.com/nfriedly/2917ff09e7560cb0ea54694ca525de49

I initially tried to stick with something closer to the just-launch-chrome API

```js
   });
+  const fetch = require('node-fetch');
+  const details = await fetch(`http://localhost:${chrome.port}/json`).then(res => res.json());
+  const browserWSEndpoint = details[0].webSocketDebuggerUrl;
   const browser = await Browser.connect(browserWSEndpoint, {
```

But, it didn't seem to be able to connect to the browser. The `details[0].webSocketDebuggerUrl` was definitely a websocket URL, but perhaps it wasn't the right one.

~When complete, this should fix #44~

Update: it's complete. Some tests are still failing, but they also fail on windows and in CI.  Fixes #44

### CODE REVIEW

**Comment by nfriedly** [comment]
Ok, I got on a windows machine and checked out master, and ran the tests there, and got the exact same set of failures: https://gist.github.com/nfriedly/9e3c748810a77b9bb827d64612df81bb#file-wombat-test-results-windows-master-txt

I then checked out this branch and again got the same set of failures: https://gist.github.com/nfriedly/9e3c748810a77b9bb827d64612df81bb#file-wombat-test-results-windows-chrome-launcher-txt

So, I guess there is something else wrong here that is not macOS-specific - although I do see that almost all of the tests are passing on travis - https://travis-ci.org/github/webrecorder/wombat/builds

**Comment by ikreymer** [comment]
Hi, thanks for taking a look at this!
We're not really using travis anymore, as there is a limit to how much it can be used.
We'll probably migrate to github actions soon... I'll be able to take a further look in a few days.

Out of curiosity, are you using wombat directly? separate from other tools, like pywb or replayweb.page? if so, curious about your use case!

**Comment by nfriedly** [comment]
I'm not actually using wombat at the moment, but I'm starting to think I should scrap my code and just embed a copy of wombat instead.

I wrote a tool called unblocker, https://github.com/nfriedly/node-unblocker - it's less for archival and more aimed at people behind internet filters or hitting geoip issues. Until recently, it was exclusively server-side, but last year I added some injected JS to make WebSockets go through the proxy server and in the last few weeks I've been working on other client-side scripts. I got a lot of things working, but hit some issues and one user pointed me to a site that uses wombat and worked properly where my code was failing. 

One thing I was doing was wrapping all site JS in an IIFE that uses local variables for window, document, and location, and sets them to Proxies that allow me to handle gets and sets of window.location and the like. But I hit an issue with one site where it was walking up the DOM tree and comparing every `element.parentNode` to `document` to know when to stop. My proxy failed that comparison and broke the script. So I decided to see if Wombat worked there, and if so, how. But it hit the `<a href="#">` issue that I initially reported.

I thought I could fix it, but wanted to start with a test case first, and so I haven't gotten to the fixing stage yet...

**Comment by nfriedly** [comment]
Oh, and I might be able to help out with the github actions, I've had to do the same thing for a number of my projects recently. I'll let you know if I can get to it, but I'm about out of time for the moment...

**Comment by nfriedly** [comment]
Progress!

I hadn't been running the build script first. After running `npm run build-full-test`, windows gets the same results as CI - `setup-initialization › using _WBWombatInit as a plain function: should add the property _wb_wombat to the window which is an object containing the exposed function` fails but all others pass.

macOS gets that failure + everything in `direct-wombat-util-fns` - but all the rest of the tests pass!

**Comment by nfriedly** [comment]
Two more updates:

1) I hadn't noticed that the direct-wombat-util-fns tests actually failed on travis ci also. So, my macbook is getting the same set of results as linux, with this PR. So I think it's ready to go in that respect.

2) Windows didn't actually finish running the tests. I went back through my logs to see if that test failed or passed there and realized that it said it had stopped with SIGINT midways through. I gave it another go, and now it's getting the same result as CI and my mac.

So, I think this PR is good to go after all. Although we really ought to figure out the current handful of failing tests.

**Pull request merged**
